server:
   port: 8095
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/olx_login_db1
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect   
            application:
            
   application:
      name: auth-service1  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
